workflows:
  build_android:
    name: Build Android APK
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.shoulderelbow.serbia" 
    scripts:
      - npm install
      - npm install @capacitor/cli @capacitor/android
      - npx cap sync android
      - cd android
      - ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - filip.cucakovic@gmail.com
